In [2]:
import tensorflow as tf

t = tf.constant([[1,2,3],[4,5,6]])
print(t)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [9]:
tf.transpose(t)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

# Implementing Convolution Layers in Keras

In [2]:
from sklearn.datasets import load_sample_images
import tensorflow as tf

In [4]:
images = load_sample_images()["images"]
images = tf.keras.layers.CenterCrop(height=70, width=120)(images)
images.shape

TensorShape([2, 70, 120, 3])

In [5]:
conv_layer = tf.keras.layers.Conv2D(filters=32, kernel_size=7)
fmaps = conv_layer(images)

In [6]:
fmaps.shape

TensorShape([2, 64, 114, 32])